## R言語の特徴
 - 主な用途:統計分析
 - 分類:手続き型・関数型・オブジェクト指向/インタプリタ


## 基本文法:
### 変数の割り当て:
変数に値を割り当てるには、代入演算子 <- もしくは = を使用します。例えば、x <- 5 とすると変数 x に値 5 が割り当てられます。
### コメント:
コメントは#を使って記述します。#以降のテキストは無視されます。
### 関数の呼び出し:
 関数は関数名に引数をカッコで囲んで呼び出します。例えば、print("Hello, World!") は文字列を出力する関数 print を呼び出しています。
### 制御構文:
 制御構文としては、条件分岐やループがあります。if-else 文や for ループ、while ループなどがあります。
### ベクトル化演算:
 R言語ではベクトル化演算が可能であり、要素ごとの演算を行うことができます。例えば、c(1, 2, 3) + c(4, 5, 6) は c(5, 7, 9) を生成します。
## データ構造:
### ベクトル (Vector):
 ベクトルは単一のデータ型の要素の集合です。c() 関数を使って作成します。例えば、x <- c(1, 2, 3, 4, 5) は長さが5の数値ベクトルを生成します。
### リスト (List):
 リストは異なるデータ型の要素の集合です。list() 関数を使って作成します。例えば、y <- list(1, "a", TRUE) は数値、文字列、論理値の要素を持つリストを生成します。
### 行列 (Matrix):
 行列は2次元のデータ構造で、全ての要素が同じデータ型である必要があります。matrix() 関数を使って作成します。
### データフレーム (Data Frame):
 データフレームは異なるデータ型の列を持つ2次元のデータ構造です。data.frame() 関数を使って作成します。データフレームはデータ分析で最もよく使われるデータ構造の一つです。
### 因子 (Factor):
 因子はカテゴリカルなデータを表現するためのデータ型です。主に統計解析において使用されます。
これらの基本文法とデータ構造を理解することで、R言語でのデータ操作や分析を始める準備が整います。

### 基本文法の学習: R言語の基本文法やデータ構造（ベクトル、リスト、データフレームなど）に慣れる

In [6]:
# バージョン確認
version

               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.2                         
year           2023                        
month          10                          
day            31                          
svn rev        85441                       
language       R                           
version.string R version 4.3.2 (2023-10-31)
nickname       Eye Holes                   

In [7]:
library()$results[,1]

[1] "IRdisplay"     "IRkernel"      "pbdZMQ"        "repr"         
  [5] "askpass"       "backports"     "base64enc"     "bit"          
  [9] "bit64"         "blob"          "brew"          "brio"         
 [13] "broom"         "bslib"         "cachem"        "callr"        
 [17] "cellranger"    "cli"           "clipr"         "colorspace"   
 [21] "commonmark"    "conflicted"    "cpp11"         "crayon"       
 [25] "credentials"   "curl"          "data.table"    "DBI"          
 [29] "dbplyr"        "desc"          "devtools"      "diffobj"      
 [33] "digest"        "dplyr"         "dtplyr"        "ellipsis"     
 [37] "evaluate"      "fansi"         "farver"        "fastmap"      
 [41] "fontawesome"   "forcats"       "fs"            "gargle"       
 [45] "generics"      "gert"          "ggplot2"       "gh"           
 [49] "gitcreds"      "glue"          "googledrive"   "googlesheets4"
 [53] "gtable"        "haven"         "highr"         "hms"          
 [57] "htmltools"     "httr"          "httr2"         "ids"          
 [61] "ini"           "isoband"       "jquerylib"     "jsonlite"     
 [65] "knitr"         "labeling"      "lifecycle"     "lubridate"    
 [69] "magrittr"      "memoise"       "mime"          "modelr"       
 [73] "munsell"       "openssl"       "pillar"        "pkgbuild"     
 [77] "pkgconfig"     "pkgload"       "praise"        "prettyunits"  
 [81] "processx"      "progress"      "ps"            "purrr"        
 [85] "R6"            "ragg"          "rappdirs"      "rcmdcheck"    
 [89] "RColorBrewer"  "readr"         "readxl"        "rematch"      
 [93] "rematch2"      "remotes"       "reprex"        "rlang"        
 [97] "rmarkdown"     "roxygen2"      "rprojroot"     "rstudioapi"   
[101] "rversions"     "rvest"         "sass"          "scales"       
[105] "selectr"       "sessioninfo"   "stringi"       "stringr"      
[109] "svglite"       "sys"           "systemfonts"   "testthat"     
[113] "textshaping"   "tibble"        "tidyr"         "tidyselect"   
[117] "tidyverse"     "timechange"    "tinytex"       "tzdb"         
[121] "usethis"       "utf8"          "uuid"          "vctrs"        
[125] "viridisLite"   "vroom"         "waldo"         "whisker"      
[129] "withr"         "xfun"          "xml2"          "xopen"        
[133] "yaml"          "zip"           "base"          "boot"         
[137] "class"         "cluster"       "codetools"     "compiler"     
[141] "datasets"      "foreign"       "graphics"      "grDevices"    
[145] "grid"          "KernSmooth"    "lattice"       "MASS"         
[149] "Matrix"        "methods"       "mgcv"          "nlme"         
[153] "nnet"          "parallel"      "rpart"         "spatial"      
[157] "splines"       "stats"         "stats4"        "survival"     
[161] "tcltk"         "tools"         "utils"

In [8]:
p = installed.packages()
rownames( p )

[1] "IRdisplay"     "IRkernel"      "pbdZMQ"        "repr"         
  [5] "askpass"       "backports"     "base64enc"     "bit"          
  [9] "bit64"         "blob"          "brew"          "brio"         
 [13] "broom"         "bslib"         "cachem"        "callr"        
 [17] "cellranger"    "cli"           "clipr"         "colorspace"   
 [21] "commonmark"    "conflicted"    "cpp11"         "crayon"       
 [25] "credentials"   "curl"          "data.table"    "DBI"          
 [29] "dbplyr"        "desc"          "devtools"      "diffobj"      
 [33] "digest"        "dplyr"         "dtplyr"        "ellipsis"     
 [37] "evaluate"      "fansi"         "farver"        "fastmap"      
 [41] "fontawesome"   "forcats"       "fs"            "gargle"       
 [45] "generics"      "gert"          "ggplot2"       "gh"           
 [49] "gitcreds"      "glue"          "googledrive"   "googlesheets4"
 [53] "gtable"        "haven"         "highr"         "hms"          
 [57] "htmltools"     "httr"          "httr2"         "ids"          
 [61] "ini"           "isoband"       "jquerylib"     "jsonlite"     
 [65] "knitr"         "labeling"      "lifecycle"     "lubridate"    
 [69] "magrittr"      "memoise"       "mime"          "modelr"       
 [73] "munsell"       "openssl"       "pillar"        "pkgbuild"     
 [77] "pkgconfig"     "pkgload"       "praise"        "prettyunits"  
 [81] "processx"      "progress"      "ps"            "purrr"        
 [85] "R6"            "ragg"          "rappdirs"      "rcmdcheck"    
 [89] "RColorBrewer"  "readr"         "readxl"        "rematch"      
 [93] "rematch2"      "remotes"       "reprex"        "rlang"        
 [97] "rmarkdown"     "roxygen2"      "rprojroot"     "rstudioapi"   
[101] "rversions"     "rvest"         "sass"          "scales"       
[105] "selectr"       "sessioninfo"   "stringi"       "stringr"      
[109] "svglite"       "sys"           "systemfonts"   "testthat"     
[113] "textshaping"   "tibble"        "tidyr"         "tidyselect"   
[117] "tidyverse"     "timechange"    "tinytex"       "tzdb"         
[121] "usethis"       "utf8"          "uuid"          "vctrs"        
[125] "viridisLite"   "vroom"         "waldo"         "whisker"      
[129] "withr"         "xfun"          "xml2"          "xopen"        
[133] "yaml"          "zip"           "base"          "boot"         
[137] "class"         "cluster"       "codetools"     "compiler"     
[141] "datasets"      "foreign"       "graphics"      "grDevices"    
[145] "grid"          "KernSmooth"    "lattice"       "MASS"         
[149] "Matrix"        "methods"       "mgcv"          "nlme"         
[153] "nnet"          "parallel"      "rpart"         "spatial"      
[157] "splines"       "stats"         "stats4"        "survival"     
[161] "tcltk"         "tools"         "utils"

In [9]:
df = data.frame( x = 1:5, y = 6:10 )
df

x y 
1 1  6
2 2  7
3 3  8
4 4  9
5 5 10

## Rでのベクトル・行列の作成と四則演算・要素の参照【第1回】
https://ai-trend.jp/programming/r-beginner/r-1/

In [10]:
x <- c(1,2,3,4,5)

In [11]:
y <- c(1:5,3:1)

In [12]:
z <- c(rep(3,4),rep(c(1,5,10),c(2,3,4)))

In [13]:
a <- c("A","B","C")

In [14]:
x

[1] 1 2 3 4 5

In [15]:
y

[1] 1 2 3 4 5 3 2 1

In [16]:
z

[1]  3  3  3  3  1  1  5  5  5 10 10 10 10

In [17]:
a

[1] "A" "B" "C"

行列を作ってみよう

In [18]:
mat1 <- matrix(c(1:10),nrow=2,ncol=5)
mat1 <- matrix(c(1:10),2,5)
mat2 <- matrix(c(1:10),2,byrow=TRUE)
mat3 <- matrix(c(1,3,2,5,7,3,2,15,2),3,3,byrow=TRUE)

In [19]:
mat1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [20]:
mat2

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [21]:
mat3

[,1] [,2] [,3]
[1,] 1     3   2   
[2,] 5     7   3   
[3,] 2    15   2

コマンド使い方matrixmatrix(要素ベクトル,行数,列数)で行列を作成。nrow行数を返す。nrow(a)で行列aの行数を返す。ncol列数を返す。ncol(a)でaの列数を返す。byrowbyrow=TUREで要素順を変更。

行列の計算をしてみよう（四則演算）

In [22]:
mat1+mat2

[,1] [,2] [,3] [,4] [,5]
[1,] 2     5    8   11   14  
[2,] 8    11   14   17   20

In [23]:
mat1-mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  0    1    2    3   4   
[2,] -4   -3   -2   -1   0

In [24]:
mat1*mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    6   15   28    45 
[2,] 12   28   48   72   100

In [25]:
mat1/mat2

[,1]      [,2]      [,3]     [,4]      [,5]
[1,] 1.0000000 1.5000000 1.666667 1.7500000 1.8 
[2,] 0.3333333 0.5714286 0.750000 0.8888889 1.0

In [26]:
mat3%*%mat3

[,1] [,2] [,3]
[1,] 20    54  15  
[2,] 46   109  37  
[3,] 81   141  53

In [27]:
solve(mat3)

[,1]        [,2]        [,3]       
[1,] -0.39240506  0.30379747 -0.06329114
[2,] -0.05063291 -0.02531646  0.08860759
[3,]  0.77215190 -0.11392405 -0.10126582

行列内の要素を参照してみよう

In [28]:
p <- mat1[1,2]
q <- mat3[,2]
r <- mat1[1,c(2,5)]

In [29]:
p

[1] 3

In [30]:
q

[1]  3  7 15

In [31]:
r

[1] 3 9